### ISSUE TITLE
Slow sync on Android Huawei P20

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/Confidant-APP_Android#18]
**Describe the bug**
It takes about 20 minutes to pull the latest email from QQ mail to Confidant. About 20 emails.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei P20 V2.7.1.302]

**Additional context**

**Comment by qlinkDev** [comment]
Will optimize the problem
