### ISSUE TITLE
New Feature for inputing new email address

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/Confidant-APP_Android#27]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when inputting new email addresses, all the address are stick together, I don't know if the app has been able to divid different emails.

输入多个邮件地址时，请自动识别每个email地址，并建立有效的分隔，避免email地址粘连导致发送失败

**Describe the solution you'd like**

输入一个有效email地址和，app自动识别，然后缩略成有效地址，返回提示输入下一个地址，而不是粘连在一起，也不知道输对了没有。
参考gmail设计

**Describe alternatives you've considered**

**Additional context**

**Comment by qlinkDev** [comment]
copy that

**Comment by susanatqlc** [comment]
added already, ready to close this issue.
