### ISSUE TITLE
Very slow on email fetching and new email notification

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/Confidant-APP_Android#31]
**Describe the bug**

和其他客户端相比，刷新后要等很久才能收到新的email
也没有收到新email的推送

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qlinkDev** [comment]
confidant用户之间发邮件的推送已经在调试了。慢的问题 也在优化。
