### ISSUE TITLE
Improvement needed: No preview before sending out pictures, it's hard to know which pictures are sent out

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/Confidant-APP_Android#33]
**Is your feature request related to a problem? Please describe.**
发送图片的时候没有图片预览，不知道发出去了哪张。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qlinkDev** [comment]
是聊天中还是email中发送图片没有预览？我看都有预览呢。。。不太确定哪里没有预览

**Comment by susanatqlc** [comment]
File --> Local Files --> 然后里面folder的照片没有预览了
