### ISSUE TITLE
New emails received in Draft

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/Confidant-APP_Android#39]
![iMarkup_20190919_074655](https://user-images.githubusercontent.com/54051334/65195448-e7879600-dab1-11e9-8c74-aa055c2bd2dc.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qlinkDev** [comment]
copy that

**Comment by susanatqlc** [comment]
Test in new version first
