### ISSUE TITLE
Can not clear all the data in Confidant

### ISSUE THREAD

**Issue by taeyonlee** [confidantstation/Confidant-APP_Android#61]
**Is your feature request related to a problem? Please describe.**
When I type in password for reconnecting to Confidant Station (the password for activating Confidant Station), I needed to log out of our account, clear all the data, and reinstall Confidant to create a new account as the owner of the Confidant Station. 

**Describe the solution you'd like**
Add a feature allowing the user to clear the data at once. and possible to change the owner in the case when a user cant access/connect to the Confidant?

**Comment by qlinkDev** [comment]
We will consider the function of clearing data and change the owner. Thank you for your suggestion
